### ISSUE TITLE
Please Help me

### ISSUE THREAD

**Issue by tongdaitructuyen** [BotoX/Dahua-Firmware-Mod-Kit#6]
How to add FW DH_XVR5x04_EngSpnFrn_NP_V3.210.0001.8.R.20170307

Link: https://www.amazon.com/clouddrive/share/OpxMW6zPDrDt0eCQmewrX4gce9IajZz5XQrxc094orr?ref_=cd_ph_share_link_copy

i have extact, change logo, change ip default, change user default. After i have Build it, but when up to my XVR, it show "Can Not Upgrade".

Please Help me

**Comment by Churiloff** [comment]
Good afternoon! My name is Andrey, I very need an firmware which will change language with Chinese for English or Russian for the IPC-HDW1225C, IPC-HDW2228C, IPC-HFW1225M-I1, IPC-HFW2228M-I1 chambers. You can help me with an insertion of these models?
